---
- hosts: mediaservers
  remote_user: pirate
  tasks:
    - name: Test connection to remote server
      ping:

- import_playbook: storage.yml
- import_playbook: vpn.yml
- import_playbook: services.yml
