---
- hosts: mediaservers
  remote_user: pirate
  tasks:
    - name: Copy services directory to remote server
      copy:
        src: services
        dest: /var/run
      become: yes

    - name: Tear down existing services
      command: docker-compose down --remove-orphans
      args:
        chdir: /var/run/services

    - name: Create and start services
      command: docker-compose up -d
      args:
        chdir: /var/run/services
