---
- hosts: mediaservers
  remote_user: pirate
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Install ntfs-3g package
      apt:
        name: ntfs-3g

    - name: Create directory to serve as mount point
      file:
        path: /mnt/extmedia
        state: directory

    - name: Capture UUID of external drive
      shell: echo $(blkid | grep 'ntfs' | sed -E 's!^.*UUID="([^"]*)" ?.*"!\1!')
      register: echo_content

    - set_fact:
        uuid: '{{ echo_content.stdout }}'
        cacheable: yes

    - name: Mount external drive
      mount:
        path: /mnt/extmedia
        src: 'UUID={{ uuid }}'
        fstype: ntfs-3g
        opts: rw,nofail,user,exec,umask=000
        state: mounted
